on:
  push:
    branches:
      - master

jobs:
  build:
    name: "Lint, Test and Scan Dependencies"
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0

      - name: Setup Go environment
        uses: actions/setup-go@v5.2.0
        with:
          go-version: "1.22.7"

      - name: Install OSV Scanner
        run: go install github.com/google/osv-scanner/cmd/osv-scanner@v1

      - name: Run Lint, Test, and Scan Dependencies
        run: npm ci && npm run format && npm run lint && npm run test:coverage && npm run scan